[[bin]]
path = "src/main.rs"
name = "neard"

[[bin]]
path = "src/../src/main.rs"
name = "near"

[package]
name = "neard"
version = "1.4.0-beta.1"
authors = [ "Near Inc <hello@nearprotocol.com>",]
edition = "2018"

[dependencies]
actix = "0.9"
byteorder = "1.2"
easy-ext = "0.2"
rocksdb = "0.14"
log = "0.4"
git-version = "0.3.1"
futures = "0.3"
clap = "2.32"
rand = "0.7"
serde_json = "1"
lazy_static = "1.4"
dirs = "2.0.2"
borsh = "0.7.0"
tracing = "0.1.13"
tracing-subscriber = "0.2.4"

[dev-dependencies]
tempfile = "3"

[features]
adversarial = [ "near-client/adversarial", "near-network/adversarial", "near-store/adversarial",]
expensive_tests = [ "near-client/expensive_tests", "near-epoch-manager/expensive_tests", "near-chain/expensive_tests",]
metric_recorder = [ "near-network/metric_recorder", "near-client/metric_recorder",]

[dependencies.chrono]
version = "0.4.4"
features = [ "serde",]

[dependencies.serde]
version = "1"
features = [ "derive",]

[dependencies.num-rational]
version = "0.2.4"
features = [ "serde",]

[dependencies.near-actix-utils]
path = "../utils/actix"

[dependencies.near-crypto]
path = "../core/crypto"

[dependencies.near-primitives]
path = "../core/primitives"

[dependencies.near-chain-configs]
path = "../core/chain-configs"

[dependencies.near-runtime-configs]
path = "../core/runtime-configs"

[dependencies.near-store]
path = "../core/store"

[dependencies.node-runtime]
path = "../runtime/runtime"

[dependencies.near-chain]
path = "../chain/chain"

[dependencies.near-chunks]
path = "../chain/chunks"

[dependencies.near-client]
path = "../chain/client"

[dependencies.near-pool]
path = "../chain/pool"

[dependencies.near-network]
path = "../chain/network"

[dependencies.near-jsonrpc]
path = "../chain/jsonrpc"

[dependencies.near-telemetry]
path = "../chain/telemetry"

[dependencies.near-epoch-manager]
path = "../chain/epoch_manager"

[dev-dependencies.near-logger-utils]
path = "../test-utils/logger"

[dev-dependencies.testlib]
path = "../test-utils/testlib"
